# Generated by Django 2.1.7 on 2019-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('salesamount', models.IntegerField(default=0)),
                ('year', models.DateField()),
            ],
            options={
                'db_table': 'salesactivity1',
            },
        ),
    ]
