# Generated by Django 2.1.7 on 2019-06-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesactivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branches',
            table='salesactivity',
        ),
    ]
