# Generated by Django 2.1.7 on 2019-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesactivity', '0003_auto_20190601_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='year',
            field=models.DateField(auto_now=True),
        ),
    ]
