# Generated by Django 2.1.7 on 2019-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesactivity', '0004_auto_20190601_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='year',
            field=models.DateField(),
        ),
    ]
